FROM 3dot/ubuntu:latest
MAINTAINER Miran Hojnik <docker@3dot.net>

#Configure node source repo
RUN wget -q https://deb.nodesource.com/setup | sudo bash -

#Install node.js
RUN apt-get install -y nodejs build-essential